### ISSUE TITLE
Deploy_service working in node v16 but not v18

### ISSUE THREAD

**Issue by iqbalbaharum** [fluencelabs/cli#120]
**Describe the bug**
`aqua remote deploy_service` is working in node v16, but is not working in node v18.
Digging in using `--log-level all`, i found something seems weird.

`Uncaught TypeError: RequestInit: duplex option is required when sending a body.`

A bit of googling around, there is instances that happen in v18 of node. So i try to downgrade to v16 and it work.

**To Reproduce**
1. Make sure your machine have node v18
2. Clone any of the quick start examples. I use the greetings.
3. Build
4. `aqua remote deploy_service`

**Expected behavior**
It should successfully deploy the service to the fluence node.

**Desktop:**
 - OS: MacOS Monteray
 - Aqua cli: 0.9.2

**Comment by shamsartem** [comment]
We plan to update fluence-js soon and when we update it in aqua cli and in this repo - this issue might be resolved

**Comment by shamsartem** [comment]
Currently the new way of installing cli is like this https://github.com/fluencelabs/cli#using-install-script
So the nodejs runtime is shiped together with the cli code and you don't have to even care about what nodejs version you use in your system
