### ISSUE TITLE
XDG conformance for configuration/cache folders

### ISSUE THREAD

**Issue by cab404** [fluencelabs/cli#557]
Fluence creates its settings and cache directory in ~/.fluence — ignoring XDG environment variables.
XDG is a well established specification, supported by major Linux distributions, allowing for easier cache cleanup, less clutter and predictable config locations.

https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by shamsartem** [comment]
@cab404 nice suggestion, I will add this to backlog and I think we can fix this at some point. Currently you can use `FLUENCE_USER_DIR` env variable which already exists to specify the dir where you want to place .fluence dir
