### ISSUE TITLE
Add support for `armv7l`

### ISSUE THREAD

**Issue by JMTK** [fluencelabs/cli#851]
Running on a raspberry pi 4B:
```
Linux raspberrypi 5.10.103-v7+ #1529 SMP Tue Mar 8 12:21:37 GMT 2022 armv7l GNU/Linux
```

```bash
jake@raspberrypi:~ $ curl -qsL https://raw.githubusercontent.com/fluencelabs/cli/main/install.sh | bash
Initiating Fluence CLI installation process...
Error: Unsupported architecture - armv7l
```

Let me know if there's any other information I can provide!

**Comment by shamsartem** [comment]
Sorry for the very late response. At this point it's not a priority for us to support all the possible architectures, but the good news is that CLI is just a node.js program, so most likely you can make it work if you replace node.js binary file that we ship in the package with a node.js binary file for your architecture. We will reconsider official support at some point in the future. Thanks for the report
