### ISSUE TITLE
After installing cli, how to start it as a provider

### ISSUE THREAD

**Issue by CodingCattwo** [fluencelabs/cli#852]
I install cli 0.15.22 in my laptop, but I dont know how to start it or run it as a provider to provide service.
I want to earn some rewards of FLT, and how to check my rewards

**Comment by shamsartem** [comment]
At this point not everybody can become a provider, but you can join the waitlist here https://fluencenetwork.notion.site/Employ-your-CPUs-with-Fluence-9e721f2c99c944e68e1fc8aaf5a7d96f

As for Fluence CLI - basically all relevant commands start with the word provider. You can read about it in the --help for example

Sorry for the very late response
