### ISSUE TITLE
failed on following the "Getting Started" docs because `wasm32-wasi` is not installed automatically.

### ISSUE THREAD

**Issue by STRRL** [fluencelabs/cli#915]
Hi team!

I am exploring the fluence and trying to build my first application on it.

I followed this doc: https://fluence.dev/docs/build/overview/getting_started

I get lots of build errors because I already get rust setup up on my machine  but `wasm32-wasi` support is not installed by default.

I saw some codes to setup rust but I think maybe my situation is not covered.

https://github.com/fluencelabs/cli/blob/7605eae0960a2b446433b205035cd124f43168e9/src/lib/rust.ts#L102-L120

**Comment by STRRL** [comment]
or append `target = "wasm32-wasi"` in `Cargo.toml` would also resolve this issue.

**Comment by STRRL** [comment]
how do you think about it?

I am glad to open a PR to address it.

**Comment by shamsartem** [comment]
thanks for your concern, sorry for answering super late. Soon this part will be completely removed in favor of renting VMs using a website UI
